name: simclr-env
channels:
  - pytorch
dependencies:
  # System related
  - python=3.7
  - pip
  - build
  - ipykernel
  - gcsfs
  - pyyaml
  - types-pyyaml
  # Scipy stack
  - numpy
  - matplotlib
  - scikit-learn
  - pandas
  # Deep learning
  - pytorch
  - torchvision
  - cudatoolkit=11.3  # 'cudatoolkit=11.3' if you have a gpu else 'cpuonly'
  - tensorboard
  # Others
  - tqdm
  # Testing
  - pytest
  - pytest-cov
  - pytest-mock
  # Formating, linting
  - mypy
  - pylint
  - black
  - isort
  - pip:
    - torch-tb-profiler
    - google-cloud-aiplatform